### ISSUE TITLE
Auto fetch/update AML list

### ISSUE THREAD

**Issue by ysfdev2** [container23/caml#3]
## Phase 1

- [x] - Have a background process that refreshes on our local AML List from https://www.treasury.gov/ofac/downloads/sdnlist.txt
- [x] - Perform a checksum on the downloaded `sdnlist.txt` file against the source [checksums list](https://home.treasury.gov/policy-issues/financial-sanctions/specially-designated-nationals-list-sdn-list/hash-values-for-ofac-sanctions-list-files)
- [x] - Sample sdnlist.txt SHA-256: c922330c59cfb8ccdf553a6351d857442bac0140660a2d9933900841a0e605d8
- [x] - If the checksums matched then save new file as latest, otherwise discard new update and try again
